import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center min-h-screen bg-gray-100`}
      >
        {/* Mobile container */}
        <div className="w-[393px] h-[852px] relative overflow-hidden bg-white border border-gray-300 shadow-lg">
          {/* Header (optional) */}
          <header className="absolute top-0 left-0 w-full z-10">
            {/* You can place a header here if needed */}
          </header>

          {/* Main content */}
          <main className="h-full w-full pb-24">{children}</main>

          {/* Footer Nav */}
          <footer className="absolute bottom-5 left-0 w-full z-20">
            <Nav />
          </footer>
        </div>
      </body>
    </html>
  );
}
